### ISSUE TITLE
Mexico > Baja California Missing Two States

### ISSUE THREAD

**Issue by ChrisChasm** [DiscipleTools/location-grid-project#1]
In GADM baja california sur only has 3 municipalities. See https://gadm.org/maps/MEX/bajacaliforniasur.html
But in reality it has 5 https://www.google.com/search?biw=1536&bih=730&tbm=isch&sa=1&ei=M31WXZjhK4Sa_Qbc5S8&q=baja+california+sur+municipios&oq=baja+california+sur+mu&gs_l=img.3.0.0j0i30j0i8i30l8.12692.13324..14562...0.0..0.243.643.0j1j2......0....1..gws-wiz-img.......0i5i30.bgrOT-YYZgc

![MEX_bajacaliforniasur_divs](https://user-images.githubusercontent.com/7318348/63265007-c11fd200-c249-11e9-922d-4d46bf6f8efa.png)

![Screen Shot 2019-08-19 at 6 22 28 AM](https://user-images.githubusercontent.com/7318348/63265013-c5e48600-c249-11e9-9e29-ad40faeedf06.png)

This highlights the needed process for upgrading the location-grid when these variances are found out.

**Comment by ChrisChasm** [comment]
Steps to make the upgrade:
- Add new records to data table.
- Find new polygons and create new polygons keyed to the location grid.
- Upload new version to mirrors
- Output a new set of records for disciple-tools-theme-data repo
- Write a migration for Disciple Tools mapping section so all themes are upgraded.

**Comment by mikeallbutt** [comment]
> Steps to make the upgrade:
> 
> * Add new records to data table.
> * Find new polygons and create new polygons keyed to the location grid.
> * Upload new version to mirrors
> * Output a new set of records for disciple-tools-theme-data repo
> * Write a migration for Disciple Tools mapping section so all themes are upgraded.

Sounds like a good plan @ChrisChasm.

**Comment by ChrisChasm** [comment]
Okay, these polygons and database updated are added into v2.
