### ISSUE TITLE
Morocco - GADM using old (pre-2015 restructure) maps

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/location-grid-project#2]
In 2015, Morocco officially restructured the country and all the maps changed.  GADM data uses old maps.

https://en.wikipedia.org/wiki/Regions_of_Morocco

Amcharts have correct 2015 mapping: https://www.amcharts.com/svg-maps/?map=morocco2015

GADM pre-2015 map:
![Morocco - GADM map pre-2015 ](https://user-images.githubusercontent.com/25323324/63593672-5acde300-c5ac-11e9-813f-f3543baee8dd.png)

**Comment by ChrisChasm** [comment]
![220px-Morocco_Regions_2015](https://user-images.githubusercontent.com/7318348/113440130-0c4c1180-93a9-11eb-9422-5359adebd1af.png)
![300px-Tasgiwin_n_Murakuc_-_Regions_of_Morocco](https://user-images.githubusercontent.com/7318348/113440133-0e15d500-93a9-11eb-8f57-1091a302b6ca.png)
